apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  label: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template: 
    metadata:
      label: 
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nguyenle510/lab:1.0.0-13
        ports:
        - containerPort: 8080
